version: '3.8'

services:
  backend:
    build: .
    container_name: him-backend
    ports:
      - "8080:8080"
    environment:
      # CRITICAL FIX: The application.properties file is looking for variables
      # starting with 'MYSQL'. We must define these variables here using
      # your actual Railway connection details.
      MYSQLHOST: mysql.railway.internal # e.g., shinkansen.proxy.rwy.net (get this from Railway)
      MYSQLPORT: 3306
      MYSQLDATABASE: railway # Ensure this matches your database name on Railway
      MYSQLUSER: railway
      MYSQLPASSWORD: yIrccbowFzJbOVYIeEwekVKjFGLbibgs

    # We remove the depends_on block and the entrypoint sleep
    # because the DB is managed externally and doesn't need a local health check.
    # We keep the simple ENTRYPOINT defined in the Dockerfile.

# Remove the volumes block since we are no longer managing a local database volume
# volumes:
#   db-data:
