version: '3.8'

services:
  backend:
    build: .
    container_name: him-backend
    ports:
      - "8080:8080"
    environment:
      MYSQLHOST: shinkansen.proxy.rlwy.net     # Railway DB host
      MYSQLPORT: 32755                         # Railway DB port
      MYSQLDATABASE: railway                   # Railway DB name
      MYSQLUSER: root                          # Railway DB username
      MYSQLPASSWORD: yIrccbowFzJbOVYIeEwekVKjFGLbibgs  # Railway DB password
