version: '3.8'

services:
  db:
    image: mysql:8
    container_name: him-db
    environment:
      MYSQL_DATABASE: himdb
      MYSQL_ROOT_PASSWORD: 491Jacaranda!
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: him-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/himdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 491Jacaranda!
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
